export const ERRORCODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  CONFLICT_ERROR: "CONFLICT_ERROR",
  ORDER_ALREADY_PAID: "ORDER_ALREADY_PAID",
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
} as const;
