export const ERRORCODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  CONFLICT_ERROR: "CONFLICT_ERROR",
  ORDER_ALREADY_PAID: "ORDER_ALREADY_PAID",
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  INVALID_GATEWAY: "INVALID_GATEWAY",
  PAYMENT_INITIATION_FAILED: "PAYMENT_INITIATION_FAILED",
  USER_PAYMENT_FAILED: "USER_PAYMENT_FAILED",
  ALL_GATEWAY_FAILED: "ALL_GATEWAYS_FAILED",
  GATEWAY_ERROR: "GATEWAY_ERROR",
} as const;
